### ISSUE TITLE
Latest Build failed

### ISSUE THREAD

**Issue by granicus422** [face-it/Hangfire.Tags#23]
@erwin-faceit Looks like the latest build failed.  Something wrong with the API key.  Also looks like it needs the version # for the main package bumped to 1.6.4.  Thanks!

**Comment by erwin-faceit** [comment]
Nope, that's not it. The problem is that somebody already uses the name Hangfire.Tags.MySql on nuget, and it's not me. So I either need to change the name for your package, but first I've contacted them by e-mail. If I'm not hearing anything this week, I think I'll rename your package to Hangfire.Tags.Providers.MySql or something like that.
