### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by wellingtonjhn** [face-it/Hangfire.Tags#69]
Hi,

Any plans for MongoDB support?

Thank you.

**Comment by erwin-faceit** [comment]
Well, I've just pushed a MongoDB version, which requires the beta for Hangfire 1.8. Since the author of Hangfire has made a prefix reservation on Nuget, I can't actually upload it to Nuget now.

You can download the package here: https://ci.appveyor.com/project/faceit/hangfire-tags/branch/mongodb/artifacts. Let me know how it goes!

**Comment by erwin-faceit** [comment]
After a chat with the author of Hangfire, I've had to decide to rename all Hangfire.Tags packages to FaceIT.Hangfire.Tags. I've published the mongo package as well: https://www.nuget.org/packages/FaceIT.Hangfire.Tags.Mongo/

**Comment by wellingtonjhn** [comment]
Thank you.

I will try this new version.

**Comment by erwin-faceit** [comment]
Have you been able to test this version?
