### ISSUE TITLE
.net framework

### ISSUE THREAD

**Issue by zhyueyueniao** [face-it/Hangfire.Tags#7]
nuget 没有.net framework版本的，可以添加一个不

**Comment by erwin-faceit** [comment]
My Chinese is not that good, but Google translate tells me that I could add a .NET Framework version to the nuget package? I don't have to, because it's for .NET Standard 2.0, which means you can use it with .NET Framework 4.7.2 or higher. 
If you need this library for lower .NET Frameworks version, please download the source and compile it. It should just work

**Comment by zhyueyueniao** [comment]
Thank you. I've compiled version 4.5
