### ISSUE TITLE
IdExtensions.Clean makes it difficult to grok a large number of tags

### ISSUE THREAD

**Issue by drewburlingame** [face-it/Hangfire.Tags#71]
[IdExtensions.Clean](https://github.com/face-it/Hangfire.Tags/blob/master/src/FaceIT.Hangfire.Tags/Extensions/IdExtensions.cs#L14) lower cases words and removes all punctuation except `-`.  This makes it difficult to grok a large collection of tags.  Keeping CamelCase names would be a big help and being able to use punctuation to categorize tags would be helpful.  For example, we'd like to be able to "tenant: {tenantId}"

What is the purpose of this seemingly aggressive clean?  Is there an option to not clean the names?

Thanks,
Drew

**Comment by erwin-faceit** [comment]
Hangfire does the same, it's because not every backend is case sensitive, so this makes it uniform. Making it all lower is the easiest method to make it consistent on different backend types.

I have just added a Clean property to the TagsOptions class, with a default of both lowercase and punctuation, but it also has options to only use lowercase, only remove punctuation, or don't touch the tag. I did however NOT implemented case sensitive searching for the backend engines.

The implementation is at the moment only available in the 1.8.2 hangfire preview packages. Let me know what you think after review/testing!

**Comment by drewburlingame** [comment]
Thanks for your quick response to this.  I'd like to test it but I'm unable to find the a 1.8.2 preview package on nuget.  

I'm using Hangfire.Tags.PostgreSql 1.9.6.  Will that work with the preview package or should I downgrade to a different version?

<img width="882" alt="image" src="https://github.com/face-it/Hangfire.Tags/assets/103345/27424def-4631-4385-9c77-beb4f21a4443">

**Comment by erwin-faceit** [comment]
Right, to makes things even more difficult, I had to change the package name, because the Hangfire prefix is now reserved.

Prepend FaceIT to the used packages.

**Comment by drewburlingame** [comment]
Thanks.  It'll probably be tomorrow before I can give it a go.

**Comment by erwin-faceit** [comment]
Did you already find the time to give this a go?

**Comment by drewburlingame** [comment]
I wasn't able to before holiday and then it dropped off my radar.  Back on radar.  I'll give it a go by Monday.

**Comment by drewburlingame** [comment]
Works like a charm.  Thank you!  Do you want to close the issue now or wait until the feature is not in a pre-release

**Comment by erwin-faceit** [comment]
Closing it now, the 1.8 version seems pretty stable, so I’ll probably push a release out next week.
