### ISSUE TITLE
Could not load file or assembly 'Hangfire.PostgreSql, Version=1.9.5.0

### ISSUE THREAD

**Issue by leorg99** [face-it/Hangfire.Tags#72]
Hi - I am having an issue with FaceIT.Hangfire.Tags.PostgreSql package v1.9.7-beta.2 and Hangfire.PostgreSq v1.20.0. 
When this line gets executed:
 ```
app.MapHangfireDashboardWithAuthorizationPolicy(string.Empty);
```
I get a `FileNotFoundException`:
```
Could not load file or assembly 'Hangfire.PostgreSql, Version=1.9.5.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

I see that v1.9.5 is a dependency in the FaceIT.Hangfire.Tags.PostgreSql library, but I thought referencing v1.20.0 would override that? 
I created a sample app that will throw the exception when you run it: https://github.com/LeorGreenberger/HangfireTagsIssue

**Comment by erwin-faceit** [comment]
Thank you for the sample application. I actually can't really understand the reason this exception occures, but I did notice that Hangire.PostgreSQL is updated to Hangfire.Core >= 1.8.0 on version 1.20.0. 

So I've updated my library to reference version 1.20.0, and updated the test application to require version 1.20.2, and that works. Not a real test though, since those versions only differ in minor version number. Let's hope this also works for future updates.
