### ISSUE TITLE
How to have default tags

### ISSUE THREAD

**Issue by fairking** [face-it/Hangfire.Tags#87]
I cannot understand how tags work. I have setup the hangfire:
```c#
.UseTagsWithSql()
```
And added a tag against the task (based on the docs):
```c#
public class MyService
{
    [Tag("{0}")]
    public async Task MyTask(CancellationToken cancellation)
    {
        // Do stuff ...
    }
}
```

As a result I got this:
![image](https://github.com/face-it/Hangfire.Tags/assets/13495631/bd75a7a6-6939-48e7-b0cd-4eec5cc1bcd5)

Is there any way to skip marking all my methods with `[Tag]` but to tell to create tags automatically based on `Class.Method` name?

Otherwise I have to apply tags to every method like that:
```c#
[Tag(nameof(MyService), nameof(MyTask))]
// or
[Tag($"{nameof(MyService)}.{nameof(MyTask)}")]
```

**Comment by erwin-faceit** [comment]
Class method name is currently not a thing. The argument use used is put in a string.Format with the arguments, so what you’re seeing now makes perfect sense. 

I would say, roll your own which determines the name of the method, then calls something like jobId.AddTags.  Your own attribute could then be added a default attribute to Hangfire instead of adding it to every job.
