### ISSUE TITLE
Allow reuse of RouteCollectionExtensions

### ISSUE THREAD

**Issue by drewburlingame** [face-it/Hangfire.Tags#95]
We're looking to add some components to the job pages and we like the approach this library used.  We'd like to do the same and reuse the components you've created.  Would you be amenable to making RouteCollectionExtensions, Resource and EmbeddedResourceDispatcher public?

**Comment by erwin-faceit** [comment]
I’ve actually not written that myself, but copied that from [Hangfire.Console](https://github.com/pieceofsummer/Hangfire.Console/tree/master/src/Hangfire.Console). Feel free to copy those yourself.

I understand reuse would be preferred, but I’d also think it’s better to extract that code into another library which can be used as dependency, instead of making your code dependable on Hangfire.Tags.

**Comment by drewburlingame** [comment]
Fair enough and we already have copied them.  Thanks for your work on the tags.
